[package]
name = "easytier-win-client"
version = "0.1.0"
edition = "2021"
default-run = "easytier-win-client"

[lib]
name = "easytier_win_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "easytier-win-client"
path = "src/main.rs"

[[bin]]
name = "easytier-service"
path = "src/service_main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tauri = { version = "2", features = ["tray-icon", "image-png"] }
wait-timeout = "0.2"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls"] }
zip = "2"

[target.'cfg(windows)'.dependencies]
windows-service = "0.7"
named_pipe = "0.4"
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Pipes", "Win32_System_IO", "Win32_System_Threading"] }
