import { useEffect, useMemo, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
type Status = 'running' | 'stopped' | 'starting' | 'stopping' | 'failed';
type Instance = { id: string; name: string; status: Status; address: string; peers: number; config: string };
const config = '[network]\nname = "我的网络"\n';
const initial: Instance[] = [{ id: 'default', name: '我的网络', status: 'stopped', address: '10.144.144.10', peers: 0, config }];
const load = <T,>(k: string, d: T): T => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(d)) as T; } catch { return d; } };
export default function App() {
 const [instances,setInstances]=useState(()=>load('easytier.instances',initial)); const [active,setActive]=useState(()=>load('easytier.active','default')); const current=useMemo(()=>instances.find(i=>i.id===active)||instances[0],[instances,active]);
 useEffect(()=>localStorage.setItem('easytier.instances',JSON.stringify(instances)),[instances]); useEffect(()=>{if(current){setActive(current.id);localStorage.setItem('easytier.active',current.id)}},[current]);
 const update=(patch:Partial<Instance>)=>setInstances(xs=>xs.map(i=>i.id===current.id?{...i,...patch}:i));
 const importText=(text:string)=>update({config:text}); const clipboard=async()=>{try{importText(await navigator.clipboard.readText())}catch(e){alert(`读取剪贴板失败：${String(e)}`)}};
 const exportToml=async(copy=false)=>{try{if(copy) await navigator.clipboard.writeText(current.config); else {const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([current.config],{type:'application/toml'}));a.download=`${current.name}.toml`;a.click();URL.revokeObjectURL(a.href)}}catch(e){alert(`导出失败：${String(e)}`)}};
 const toggle=async()=>{const running=current.status==='running';update({status:running?'stopping':'starting'});try{const s=await invoke<{status:Status}>(running?'stop_instance':'start_instance',running?{id:current.id}:{id:current.id,config:current.config});update({status:s.status})}catch(e){update({status:'failed'});alert(`网络操作失败：${String(e)}`)}};
 const add=()=>{const id=crypto.randomUUID();setInstances(x=>[...x,{id,name:'新网络',status:'stopped',address:'10.144.144.10',peers:0,config}]);setActive(id)};
 if(!current)return null; return <main className="app-shell"><aside><div className="brand"><span className="brand-mark">E</span><div><strong>EasyTier</strong><small>Windows Client</small></div></div><div className="section-label">网络实例</div><nav>{instances.map(i=><button className={i.id===active?'nav-item active':'nav-item'} onClick={()=>setActive(i.id)} key={i.id}><span className={i.status==='running'?'dot on':'dot'}/>{i.name}<span className="chevron">›</span></button>)}</nav><button className="add-button" onClick={add}>＋ 新建实例</button><div className="sidebar-bottom"><button className="quiet">⚙　设置</button><span className="version">客户端 0.1.0</span></div></aside><section className="content"><header><div><p className="eyebrow">网络实例</p><h1>{current.name}</h1></div><div className="header-actions"><label className="ghost">导入配置<input hidden type="file" accept=".toml,text/plain" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(importText)}}/></label><button className="ghost" onClick={()=>void clipboard()}>剪贴板导入</button><button className={current.status==='running'?'stop':'primary'} onClick={()=>void toggle()}>{current.status==='running'?'停止网络':'启动网络'}</button></div></header><div className="status-card"><div className="status-icon">{current.status==='running'?'✓':'−'}</div><div><span className="card-label">当前状态</span><h2>{current.status==='running'?'网络运行中':current.status==='failed'?'网络启动失败':'网络已停止'}</h2><p>启动网络后，设备将加入 EasyTier 虚拟网络。</p></div><div className="status-meta"><span>虚拟地址</span><b>{current.address}</b></div></div><div className="section-heading"><div><h2>概览</h2><p>查看当前实例的连接状态和网络信息</p></div></div><div className="metrics"><article><span>对等节点</span><strong>{current.peers}</strong><small>已连接</small></article><article><span>网络延迟</span><strong>—</strong><small>暂无数据</small></article><article><span>上传 / 下载</span><strong>0 B/s</strong><small>实时速率</small></article></div><div className="section-heading config-heading"><div><h2>配置</h2><p>支持 TOML 文件或剪贴板导入导出</p></div><span><button className="text-button" onClick={()=>void exportToml()}>导出 TOML　↗</button><button className="text-button" onClick={()=>void exportToml(true)}>复制 TOML</button></span></div><div className="config-grid"><button className="config-card" onClick={()=>void clipboard()}><span className="config-icon">◎</span><div><b>导入配置</b><small>从剪贴板读取 TOML</small></div><span>›</span></button></div></section></main>;
}
