import { useMemo, useState } from 'react';

type Instance = { id: string; name: string; status: 'running' | 'stopped'; address: string; peers: number };
const initial: Instance[] = [{ id: 'default', name: '我的网络', status: 'stopped', address: '10.144.144.10', peers: 0 }];

export default function App() {
  const [instances, setInstances] = useState(initial); const [active, setActive] = useState('default');
  const current = useMemo(() => instances.find(i => i.id === active)!, [instances, active]);
  const toggle = () => setInstances(xs => xs.map(i => i.id === active ? {...i, status: i.status === 'running' ? 'stopped' : 'running'} : i));
  const add = () => { const id = crypto.randomUUID(); setInstances(xs => [...xs, {id, name: '新网络', status:'stopped', address:'10.144.144.10', peers:0}]); setActive(id); };
  return <main className="app-shell"><aside><div className="brand"><span className="brand-mark">E</span><div><strong>EasyTier</strong><small>Windows Client</small></div></div><div className="section-label">网络实例</div><nav>{instances.map(i => <button className={i.id === active ? 'nav-item active' : 'nav-item'} onClick={() => setActive(i.id)} key={i.id}><span className={i.status === 'running' ? 'dot on' : 'dot'} />{i.name}<span className="chevron">›</span></button>)}</nav><button className="add-button" onClick={add}>＋ 新建实例</button><div className="sidebar-bottom"><button className="quiet">⚙　设置</button><span className="version">客户端 0.1.0</span></div></aside><section className="content"><header><div><p className="eyebrow">网络实例</p><h1>{current.name}</h1></div><div className="header-actions"><button className="ghost">导入配置</button><button className={current.status === 'running' ? 'stop' : 'primary'} onClick={toggle}>{current.status === 'running' ? '停止网络' : '启动网络'}</button></div></header><div className="status-card"><div className="status-icon">{current.status === 'running' ? '✓' : '−'}</div><div><span className="card-label">当前状态</span><h2>{current.status === 'running' ? '网络运行中' : '网络已停止'}</h2><p>{current.status === 'running' ? '所有服务正常，可以访问虚拟网络。' : '启动网络后，设备将加入 EasyTier 虚拟网络。'}</p></div><div className="status-meta"><span>虚拟地址</span><b>{current.address}</b></div></div><div className="section-heading"><div><h2>概览</h2><p>查看当前实例的连接状态和网络信息</p></div><button className="text-button">查看日志　›</button></div><div className="metrics"><article><span>对等节点</span><strong>{current.peers}</strong><small>已连接</small></article><article><span>网络延迟</span><strong>—</strong><small>暂无数据</small></article><article><span>上传 / 下载</span><strong>0 B/s</strong><small>实时速率</small></article></div><div className="section-heading config-heading"><div><h2>配置</h2><p>编辑网络参数，支持 TOML 文件或剪贴板导入</p></div><button className="text-button">导出 TOML　↗</button></div><div className="config-grid"><button className="config-card"><span className="config-icon">◎</span><div><b>基础配置</b><small>网络名称、密钥、虚拟地址</small></div><span>›</span></button><button className="config-card"><span className="config-icon">⌘</span><div><b>连接设置</b><small>节点、监听器、代理网络</small></div><span>›</span></button><button className="config-card"><span className="config-icon">≋</span><div><b>高级设置</b><small>路由、协议与性能选项</small></div><span>›</span></button></div></section></main>;
}
